### ISSUE TITLE
No code provided for claimUtil.js in React step-by-step CIAM tutorial

### ISSUE THREAD

**Issue by yuazhou** [Azure-Samples/ms-identity-ciam-javascript-tutorial#60]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> In Tutorial: Prepare a React single-page app (SPA) for authentication in a customer tenant, code for claimUtil.js was not provided. 

### Any log messages given by the failure
> N/A

### Expected/desired behavior
> Should provide code for claimUtil.js 

### OS and Version?
> N/A

### Versions
> N/A

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by OwenRichards1** [comment]
Thanks for the feedback @yuazhou - the claim.Util.js file is now located on the following page:

https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-single-page-app-react-sign-in-configure-authentication
